[package]
name = "voice"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
cpal = "0.15.3"
futures = "0.3.30"
hound = "3.5.1"
iced = { version = "0.12.1", features = ["advanced", "canvas"] }
plotters = "0.3.6"
