[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
cpal = "0.15.3"
hound = "3.5.1"
rustfft = "6.2.0"

async-channel.workspace = true
num-complex.workspace = true
