[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.16.0"
hound = "3.5.1"
rustfft = "6.3.0"

approx.workspace = true
async-channel.workspace = true
num-complex.workspace = true
num-derive.workspace = true
num-traits.workspace = true
